- name: "Install main 'lightdm' package"
  community.general.pacman:
    name: lightdm
    state: present
  become: true
  become_user: root

- name: "Install 'lightdm-gtk-greeter' package, for GUI menu and auto-login"
  community.general.pacman:
    name: lightdm-gtk-greeter
    state: present
    extra_args: "--asdeps"
  become: true
  become_user: root

- name: "Install 'accountsservice' package, to hide system users in menu"
  community.general.pacman:
    name: accountsservice
    state: present
    extra_args: "--asdeps"
  become: true
  become_user: root

