- name: "Edit block in {{ conf_file_path }}: {{ block_description }}"
  ansible.builtin.blockinfile:
    path: "{{ conf_file_path }}"
    insertafter: >-
      ^\[Seat:\*\]$
    block: "{{ block_lines }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ block_description }}"
    create: no
    state: present
  become: true
  become_user: root

