- name: "Install main 'lightdm' package"
  ansible.builtin.package:
    name: lightdm
    state: present
  become: true
  become_user: root

- name: "Install 'lightdm-gtk-greeter' package, for GUI menu and auto-login"
  ansible.builtin.package:
    name: lightdm-gtk-greeter
    state: present
  become: true
  become_user: root

