- name: "Disable auto-login in {{ lightdm_conf_path }}"
  ansible.builtin.include_tasks: edit_lightdm_conf.yml
  vars:
    block_description: "autologin-user"
    block_lines: "autologin-user="

- name: "Enable manual greeter login option in {{ lightdm_conf_path }}"
  ansible.builtin.include_tasks: edit_lightdm_conf.yml
  vars:
    block_description: "manual login option"
    block_lines: "greeter-show-manual-login=true"

- name: "Set login menu to hide users {{ login_menu_hide_users }}"
  ansible.builtin.lineinfile:
    path: "/etc/lightdm/users.conf"
    regexp: >-
      ^hidden-users=nobody nobody4 noaccess$
    line: >-
      hidden-users=nobody nobody4 noaccess {{ login_menu_hide_users }}
    create: no
    state: present
  become: true
  become_user: root

