- name: "Install main lightdm packages {{ main_lightdm_pkgs }}"
  community.general.pacman:
    name: "{{ main_lightdm_pkgs }}"
    state: present
  vars:
    main_lightdm_pkgs:
      - lightdm
      - lightdm-gtk-greeter
  become: true
  become_user: root

- name: "Set session to '{{ session }}' in {{ lightdm_conf_path }}"
  ansible.builtin.include_tasks: edit_lightdm_conf.yml
  vars:
    block_description: "user-session"
    block_lines: "user-session={{ session }}"

- name: "Enable lightdm service to start at boot"
  ansible.builtin.service:
    name: lightdm
    enabled: yes
  become: true
  become_user: root

