- name: "Disable auto-login in {{ lightdm_conf_path }}"
  ansible.builtin.include_tasks: edit_lightdm_conf.yml
  vars:
    block_description: "autologin-user"
    block_lines: "autologin-user="

- name: "Enable manual greeter login option in {{ lightdm_conf_path }}"
  ansible.builtin.include_tasks: edit_lightdm_conf.yml
  vars:
    block_description: "manual login option"
    block_lines: "greeter-show-manual-login=true"

- name: "Set login menu to hide users {{ login_menu_hidden_users | default('NONE') }}"
  ansible.builtin.lineinfile:
    path: "/etc/lightdm/users.conf"
    regexp: >-
      ^hidden-users=nobody nobody4 noaccess$
    line: >-
      hidden-users=nobody nobody4 noaccess{{ users_string }}
    create: no
    state: present
  vars:
    users_string: "{{ login_menu_hidden_users | map('regex_replace', '^', ' ') | list | join(' ') }}"
  become: true
  become_user: root
  when: login_menu_hidden_users is defined

