- name: "Disable auto-login in {{ lightdm_conf_path }}"
  ansible.builtin.include_tasks: edit_lightdm_conf.yml
  vars:
    block_description: "{{ auto_login_block_description }}"
    block_lines: "autologin-user="
    lightdm_conf_section: >-
      ^[Seat:*]$

