- name: "Disable auto-login in {{ lightdm_conf_path }}"
  ansible.builtin.include_tasks: edit_lightdm_conf.yml
  vars:
    block_description: "autologin-user"
    block_lines: "autologin-user="

- name: "Enable manual greeter login option in {{ lightdm_conf_path }}"
  ansible.builtin.include_tasks: edit_lightdm_conf.yml
  vars:
    block_description: "manual login option"
    block_lines: "greeter-show-manual-login=true"

- name: "Install '{{ accounts_svc_pkg }}' package, to hide system users in menu"
  community.general.pacman:
    name: "{{ accounts_svc_pkg }}"
    state: present
  vars:
    accounts_svc_pkg: "accountsservice"
  become: true
  become_user: root

