- name: "Install main 'lightdm' package"
  community.general.pacman:
    name: lightdm
    state: present
  become: true
  become_user: root

- name: "Install 'lightdm-gtk-greeter' package, for GUI menu and auto-login"
  community.general.pacman:
    name: lightdm-gtk-greeter
    state: present
    extra_args: "--asdeps"
  become: true
  become_user: root

- name: "Set default session to '{{ session }}'"
  ansible.builtin.include_tasks: edit_lightdm_conf.yml
  vars:
    block_description: "user-session"
    block_lines: "user-session={{ session }}"

- name: "Enable lightdm service to start at boot"
  ansible.builtin.service:
    name: lightdm
    enabled: yes
  become: true
  become_user: root

