- name: "Disable auto-login in {{ lightdm_conf_path }}"
  ansible.builtin.include_tasks: edit_lightdm_conf.yml
  vars:
    block_description: "autologin-user"
    block_lines: "autologin-user="

- name: "Enable manual greeter login option in {{ lightdm_conf_path }}"
  ansible.builtin.include_tasks: edit_lightdm_conf.yml
  vars:
    block_description: "manual login option"
    block_lines: "greeter-show-manual-login=true"

- name: "Set login screen background image to {{ login_screen_image_path }}"
  ansible.builtin.include_tasks: edit_lightdm_conf.yml
  vars:
    conf_file_path: "/etc/lightdm/lightdm-gtk-greeter.conf"
    block_description: "login screen background image"
    block_lines: "background={{ login_screen_image_path }}"
    insertafter: >-
      ^\[greeter:\*\]$
  when: (login_screen_image_path)

- name: "Install '{{ accounts_svc_pkg }}' package, to hide system users in menu"
  community.general.pacman:
    name: "{{ accounts_svc_pkg }}"
    state: present
  vars:
    accounts_svc_pkg: "accountsservice"
  become: true
  become_user: root

