- name: "Edit block in {{ lightdm_conf_path }}: {{ block_description }}"
  ansible.builtin.blockinfile:
    path: "{{ lightdm_conf_path }}"
    insertafter: >-
      ^\[Seat:\*\]$
    block: "{{ block_lines }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ block_description }}"
    create: no
    state: present
  vars:
    lightdm_conf_path: "/etc/lightdm/lightdm.conf"
  become: true
  become_user: root

