- name: "LightDM: install 'lightdm' package"
  community.general.pacman:
    name: lightdm
    state: present
  become: true
  become_user: root

- name: "Configure LightDM for automatic login for user '{{ auto_login_user_name }}'"
  ansible.builtin.include_tasks: config_auto_login.yml
  when: (auto_login_user_name)

- name: "Configure LightDM for graphical greeter (disable automatic login)"
  ansible.builtin.include_tasks: config_greeter.yml
  when: not (auto_login_user_name)

- name: "Enable lightdm service to start at boot"
  ansible.builtin.service:
    name: lightdm
    enabled: yes
  become: true
  become_user: root

